### ISSUE TITLE
How to reload?

### ISSUE THREAD

**Issue by belovebist** [bennypowers/lit-apollo#14] opened 2018-09-16 16:06 UTC
Hi,

Thank you writing this library.

How do I refetch same query with same set of variables? I'm using lit-element 0.6.0 and lit-apollo 0.6.6-dev. I've tried reassigning to both variables and queries in a hope that it'd trigger fetch. Also tried using fetchMore, but it didn't work.

**Comment by bennypowers** [comment] 2018-09-16 17:52
Thanks for stopping by 😄 

The [`fetchMore`](https://github.com/bennypowers/lit-apollo/blob/master/apollo-query.js#L248) method on ApolloQuery should cover your case

If that doesn't work, please provide a reproduction on glitch.com

You might also want to use the [`executeQuery`](https://github.com/bennypowers/lit-apollo/blob/1a083aa3169b5b4277edc14743a8f66e1437f51f/apollo-query.js#L212) method to do a one-off fetch.

**Comment by belovebist** [comment] 2018-09-21 19:36
Hi,

I'll not be able to reproduce the issue because of lack of time. Anyway, I think there may have been some changes in lit-element itself and this library is not working as expected with new version of lit-element. In case of mutation, it says ```
updating-element.js:386 Uncaught (in promise) TypeError: this.update is not a function
    at HTMLElement._validate (updating-element.js:386)
    at HTMLElement._invalidate (updating-element.js:368)
```.
I see you've set `this.update = undefined;` in ApolloMutation. This will obviously override the update method used by LitElement. I guess you need to update lit-apollo to use latest lit-element.

**Comment by bennypowers** [comment] 2018-09-22 16:54
@belovebist That's a good catch. Indeed, LitElement provides an `update` method for classes, which conflicts with apollo's `update` function. I'm going to look into fixing this without having to issue a major version.

**Comment by bennypowers** [comment] 2018-09-23 07:43
I've just pushed [v0.6.7](https://www.npmjs.com/package/lit-apollo) which renames ApolloMutation's `update` method to `onUpdate`. I'm closing now since this should fix the problem, please don't hesitate to reopen if that's not the case.

**Closed by bennypowers** 2018-09-23 07:43 UTC

**Comment by belovebist** [comment] 2018-09-24 14:44
Hi @bennypowers ,

I'd just like to add a comment here instead of creating new issue as it's related to changes in LitElement. I saw that you've raised a issue https://github.com/Polymer/lit-element/issues/196.
I just wanted to know if you're planning to change your elements to use explicit de-structuring of props like` { data, loading, error } = this`. If yes, how long would it take.
I'm currently overriding shouldUpdate method like:
```
shouldUpdate(changedProps) {
    const { data, loading, error, networkStatus } = this;
    return !!data || !!error || loading != null;
}
```
And have to use changedProps like:
if (changedProps.has("myProp")) {
    const { myProp } = this;
    // use myProp ...
}

Kind Regards,
Belove
